---
- name: update all machines
  sudo: yes
  hosts: all
  roles:
    - update

- name: deploy elasticsearch cluster
  sudo: yes
  hosts: elasticsearch
  roles:
    - java
    - elasticsearch

- name: set up elasticsearch plugins
  sudo: yes
  hosts: masters
  roles:
    - elasticsearch-plugins
